"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-05-20 18:00:16.997890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('commander','operator')", name='ck_person_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.CheckConstraint("kind IN ('morning','noon','night')", name='ck_shift_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'kind', name='uq_shift_date_kind')
    )
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_date'), ['date'], unique=False)

    op.create_table('presence_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='ck_period_end_ge_start'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presence_period', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presence_period_person_id'), ['person_id'], unique=False)

    op.create_table('shift_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("slot IN ('commander','operator')", name='ck_assign_slot'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id', 'person_id', name='uq_assign_shift_person'),
    sa.UniqueConstraint('shift_id', 'slot', 'position', name='uq_assign_shift_slot_position')
    )
    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_assignment_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_assignment_shift_id'), ['shift_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_assignment_shift_id'))
        batch_op.drop_index(batch_op.f('ix_shift_assignment_person_id'))

    op.drop_table('shift_assignment')
    with op.batch_alter_table('presence_period', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presence_period_person_id'))

    op.drop_table('presence_period')
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_date'))

    op.drop_table('shift')
    op.drop_table('person')
    op.drop_table('edit_log')
    # ### end Alembic commands ###
